name: Build

# TMP validate the graphql query
on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Get milestone number (do not exist)
      env:
        VERSION: 0.1.8
      run: |
        MILESTONE_NUMBER=$(gh api graphql -f query='
          query($version: String!) {
            repository(owner: "maxGraph", name: "maxGraph") {
              milestones(first: 1, query: $version) {
                nodes { number }
              }
            }
          }' -f version="${{ env.VERSION }}" --jq '.data.repository.milestones.nodes[0].number')
        echo "MILESTONE_NUMBER_1=${MILESTONE_NUMBER:-unknown}" >> $GITHUB_ENV

    - name: Get milestone number (exist)
      env:
        VERSION: 0.15.0
      run: |
        MILESTONE_NUMBER=$(gh api graphql -f query='
          query($version: String!) {
            repository(owner: "maxGraph", name: "maxGraph") {
              milestones(first: 1, query: $version) {
                nodes { number }
              }
            }
          }' -f version="${{ env.VERSION }}" --jq '.data.repository.milestones.nodes[0].number')
        echo "MILESTONE_NUMBER_2=${MILESTONE_NUMBER:-unknown}" >> $GITHUB_ENV

    - name: List milestone numbers
      run: |
        echo "MILESTONE_NUMBER_1=${{ env.MILESTONE_NUMBER_1 }}"
        echo "MILESTONE_NUMBER_2=${{ env.MILESTONE_NUMBER_2 }}"

