name: Generate documentation

on:
  pull_request:
    branches:
      - development
    paths:
      - '.github/workflows/generate-documentation.yml'
      - '.nvmrc'
      - 'packages/core/*'
      - 'packages/docs/*'
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm install
      - name: Build @maxgraph/core API docs
        working-directory: packages/core
        run: npm run docs:api
